# Those samples are non-production-ready templates. 
# © 2021 Amazon Web Services, Inc. or its affiliates. All Rights Reserved. 
# This AWS Content is provided subject to the terms of the AWS Customer Agreement available at http://aws.amazon.com/agreement or 
# other written agreement between Customer and either Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

# eksctl create cluster -f ./create-cluster.yaml
# aws eks update-kubeconfig --name testing-cluster --region us-east-1

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testing-cluster
  region: us-east-1

iam:
  withOIDC: true

managedNodeGroups:
- name: nodeGroup-1
  desiredCapacity: 2
  instanceType: t3.medium
  privateNetworking: false
